export const mokuzi = {
  'ul#mokuzi': {
    listStyleType: 'none',
    border: 'solid 2px #444',
    borderTop: 'solid 0px #fff',
    padding: '0px',
    margin: '10px',
    boxShadow: '0px 3px 0px rgba(1, 1, 1, 0.3)',
  },
  'ul#mokuzi > li': { display: 'block', marginLeft: '0px' },
  'ul#mokuzi > li > a': {
    marginLeft: '-3px',
    marginTop: '-1px',
    display: 'block',
    padding: '10px',
    width: '98%',
    fontSize: ['19px', '1.2rem'],
    fontWeight: 'bold',
    background: '#b5e8ff',
    lineHeight: '1.2rem',
    textDecoration: 'none',
    boxShadow: '1px 3px 5px rgba(1, 1, 1, 0.4)',
    zIndex: 2,
  },
  'ul#mokuzi > li > ul': {
    listStyleType: 'none',
    paddingLeft: '0px',
    marginLeft: '0px',
  },
  'ul#mokuzi > li > ul > li': {
    position: 'relative',
    paddingRight: '15px',
    borderBottom: 'solid 1px #333',
    listStyleType: 'none',
    marginLeft: '0px',
  },
  'ul#mokuzi > li > ul > li:last-child': { borderBottom: 'solid 0px #fff' },
  'ul#mokuzi > li > ul > li a': {
    fontSize: ['17px', '1rem'],
    display: 'block',
    lineHeight: ['20px', '1.4rem'],
    padding: '8px',
    textDecoration: 'none',
  },
  'ul#mokuzi > li > ul > li a.big': {
    fontSize: ['19px', '1.2rem'],
    lineHeight: ['20px', '1.4rem'],
  },
  'ul#mokuzi > li > ul > li a:before, ul#mokuzi > li > ul > li a:after': {
    content: '""',
    position: 'absolute',
    borderTop: 'solid 10px transparent',
    borderRight: 'solid 10px transparent',
    borderBottom: 'solid 10px transparent',
    width: '0px',
    height: '0px',
    bottom: '8px',
  },
  'ul#mokuzi > li > ul > li a:before': {
    right: '0px',
    borderLeft: 'solid 10px #000',
  },
  'ul#mokuzi > li > ul > li a:after': {
    right: '2px',
    borderLeft: 'solid 10px #fff',
  },
};
